#!/bin/bash
# TODO: use (?) INSTALL_DIR="${2}/Applications/Unipro UGENE.app/Contents/MacOS"
INSTALL_DIR="/Applications/Unipro UGENE.app/Contents/MacOS"
SYMLINK="${HOME}/UGENE Samples"

if [ ! -e "$SYMLINK" ]
then
  ln -fs "${INSTALL_DIR}/data/samples" "$SYMLINK"
fi
