# -------------------------------------------------
# Project created by QtCreator 2009-07-07T13:37:29
# -------------------------------------------------
include (ball.pri)
SOURCES += src/BallPlugin.cpp \
    src/SES.cpp \
    src/SAS.cpp \
    src/source/COMMON/version.cpp \
    src/source/COMMON/rtti.cpp \
    src/source/COMMON/logStream.cpp \
    src/source/COMMON/hash.cpp \
    src/source/COMMON/exception.cpp \
    src/source/COMMON/constants.cpp \
    src/source/CONCEPT/visitor.cpp \
    src/source/CONCEPT/processor.cpp \
    src/source/CONCEPT/predicate.cpp \
    src/source/DATATYPE/string.cpp \
    src/source/DATATYPE/hashGrid.cpp \
    src/source/MATHS/vector4.cpp \
    src/source/MATHS/vector3.cpp \
    src/source/MATHS/surface.cpp \
    src/source/MATHS/sphere3.cpp \
    src/source/MATHS/simpleBox3.cpp \
    src/source/MATHS/quaternion.cpp \
    src/source/MATHS/plane3.cpp \
    src/source/MATHS/matrix44.cpp \
    src/source/MATHS/line3.cpp \
    src/source/MATHS/common.cpp \
    src/source/MATHS/circle3.cpp \
    src/source/MATHS/angle.cpp \
    src/source/MATHS/analyticalGeometry.cpp \
    src/source/STRUCTURE/triangulatedSurface.cpp \
    src/source/STRUCTURE/triangulatedSES.cpp \
    src/source/STRUCTURE/trianglePoint.cpp \
    src/source/STRUCTURE/triangleEdge.cpp \
    src/source/STRUCTURE/triangle.cpp \
    src/source/STRUCTURE/solventExcludedSurface.cpp \
    src/source/STRUCTURE/SESVertex.cpp \
    src/source/STRUCTURE/SESFace.cpp \
    src/source/STRUCTURE/SESEdge.cpp \
    src/source/STRUCTURE/RSVertex.cpp \
    src/source/STRUCTURE/RSFace.cpp \
    src/source/STRUCTURE/RSEdge.cpp \
    src/source/STRUCTURE/reducedSurface.cpp \
    src/source/STRUCTURE/graphVertex.cpp \
    src/source/STRUCTURE/graphFace.cpp \
    src/source/STRUCTURE/graphEdge.cpp \
    src/source/STRUCTURE/solventAccessibleSurface.cpp \
    src/source/STRUCTURE/triangulatedSAS.cpp \
    src/source/STRUCTURE/SASFace.cpp \
    src/source/STRUCTURE/SASVertex.cpp \
    src/source/STRUCTURE/SASEdge.cpp
HEADERS += src/BallPlugin.h \
    src/SES.h \
    src/SAS.h \
    src/include/BALL/COMMON/version.h \
    src/include/BALL/COMMON/rtti.h \
    src/include/BALL/COMMON/macros.h \
    src/include/BALL/COMMON/logStream.h \
    src/include/BALL/COMMON/limits.h \
    src/include/BALL/COMMON/hash.h \
    src/include/BALL/COMMON/global.h \
    src/include/BALL/COMMON/exception.h \
    src/include/BALL/COMMON/debug.h \
    src/include/BALL/COMMON/create.h \
    src/include/BALL/COMMON/constants.h \
    src/include/BALL/common.h \
    src/include/BALL/CONCEPT/visitor.h \
    src/include/BALL/CONCEPT/processor.h \
    src/include/BALL/CONCEPT/predicate.h \
    src/include/BALL/CONCEPT/forwardIterator.h \
    src/include/BALL/CONCEPT/baseIterator.h \
    src/include/BALL/CONCEPT/baseFunctor.h \
    src/include/BALL/CONFIG/config.h \
    src/include/BALL/DATATYPE/triple.h \
    src/include/BALL/DATATYPE/stringHashMap.h \
    src/include/BALL/DATATYPE/string.h \
    src/include/BALL/DATATYPE/quadruple.h \
    src/include/BALL/DATATYPE/list.h \
    src/include/BALL/DATATYPE/hashSet.h \
    src/include/BALL/DATATYPE/hashMap.h \
    src/include/BALL/DATATYPE/hashGrid.h \
    src/include/BALL/DATATYPE/forEach.h \
    src/include/BALL/MATHS/vector4.h \
    src/include/BALL/MATHS/vector3.h \
    src/include/BALL/MATHS/surface.h \
    src/include/BALL/MATHS/sphere3.h \
    src/include/BALL/MATHS/simpleBox3.h \
    src/include/BALL/MATHS/quaternion.h \
    src/include/BALL/MATHS/plane3.h \
    src/include/BALL/MATHS/matrix44.h \
    src/include/BALL/MATHS/line3.h \
    src/include/BALL/MATHS/common.h \
    src/include/BALL/MATHS/circle3.h \
    src/include/BALL/MATHS/angle.h \
    src/include/BALL/MATHS/analyticalGeometry.h \
    src/include/BALL/MATHS/vector4.h \
    src/include/BALL/MATHS/vector3.h \
    src/include/BALL/MATHS/surface.h \
    src/include/BALL/MATHS/sphere3.h \
    src/include/BALL/MATHS/simpleBox3.h \
    src/include/BALL/MATHS/quaternion.h \
    src/include/BALL/MATHS/plane3.h \
    src/include/BALL/MATHS/matrix44.h \
    src/include/BALL/MATHS/line3.h \
    src/include/BALL/MATHS/common.h \
    src/include/BALL/MATHS/circle3.h \
    src/include/BALL/MATHS/angle.h \
    src/include/BALL/MATHS/analyticalGeometry.h \
    src/include/BALL/STRUCTURE/triangulatedSurface.h \
    src/include/BALL/STRUCTURE/triangulatedSES.h \
    src/include/BALL/STRUCTURE/trianglePoint.h \
    src/include/BALL/STRUCTURE/triangleEdge.h \
    src/include/BALL/STRUCTURE/triangle.h \
    src/include/BALL/STRUCTURE/solventExcludedSurface.h \
    src/include/BALL/STRUCTURE/SESVertex.h \
    src/include/BALL/STRUCTURE/SESFace.h \
    src/include/BALL/STRUCTURE/SESEdge.h \
    src/include/BALL/STRUCTURE/RSVertex.h \
    src/include/BALL/STRUCTURE/RSFace.h \
    src/include/BALL/STRUCTURE/RSEdge.h \
    src/include/BALL/STRUCTURE/reducedSurface.h \
    src/include/BALL/STRUCTURE/graphVertex.h \
    src/include/BALL/STRUCTURE/graphFace.h \
    src/include/BALL/STRUCTURE/graphEdge.h \
    src/include/BALL/STRUCTURE/solventAccessibleSurface.h \
    src/include/BALL/STRUCTURE/triangulatedSAS.h \
    src/include/BALL/STRUCTURE/SASVertex.h \
    src/include/BALL/STRUCTURE/SASFace.h \
    src/include/BALL/STRUCTURE/SASEdge.h
OTHER_FILES += src/include/BALL/COMMON/logStream.iC \
    src/include/BALL/DATATYPE/string.iC
INCLUDEPATH += src/include
TRANSLATIONS += transl/english.ts transl/russian.ts
