/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2013 UniPro <ugene@unipro.ru>
 * http://ugene.unipro.ru
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_H_

#include <U2Test/GUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {
#undef GUI_TEST_PREFIX
#define GUI_TEST_PREFIX "GUITest_regression_scenarios_"

GUI_TEST_CLASS_DECLARATION(test_0734)
GUI_TEST_CLASS_DECLARATION(test_0928)
GUI_TEST_CLASS_DECLARATION(test_0986)
GUI_TEST_CLASS_DECLARATION(test_0986_1)
GUI_TEST_CLASS_DECLARATION(test_0986_2)
GUI_TEST_CLASS_DECLARATION(test_0986_3)
GUI_TEST_CLASS_DECLARATION(test_0986_4)

GUI_TEST_CLASS_DECLARATION(test_1001)
GUI_TEST_CLASS_DECLARATION(test_1001_1)
GUI_TEST_CLASS_DECLARATION(test_1001_2)
GUI_TEST_CLASS_DECLARATION(test_1001_3)
GUI_TEST_CLASS_DECLARATION(test_1001_4)

GUI_TEST_CLASS_DECLARATION(test_1015)
GUI_TEST_CLASS_DECLARATION(test_1015_1)
GUI_TEST_CLASS_DECLARATION(test_1015_2)
GUI_TEST_CLASS_DECLARATION(test_1015_3)
GUI_TEST_CLASS_DECLARATION(test_1015_4)

GUI_TEST_CLASS_DECLARATION(test_1021)
GUI_TEST_CLASS_DECLARATION(test_1021_1)
GUI_TEST_CLASS_DECLARATION(test_1021_2)
GUI_TEST_CLASS_DECLARATION(test_1021_3)
GUI_TEST_CLASS_DECLARATION(test_1021_4)

GUI_TEST_CLASS_DECLARATION(test_1022)

GUI_TEST_CLASS_DECLARATION(test_1199)
GUI_TEST_CLASS_DECLARATION(test_1083)
GUI_TEST_CLASS_DECLARATION(test_1093)

GUI_TEST_CLASS_DECLARATION(test_1107)

GUI_TEST_CLASS_DECLARATION(test_1113)
GUI_TEST_CLASS_DECLARATION(test_1113_1)

GUI_TEST_CLASS_DECLARATION(test_1165)

GUI_TEST_CLASS_DECLARATION(test_1189)
GUI_TEST_CLASS_DECLARATION(test_1189_1)

GUI_TEST_CLASS_DECLARATION(test_1190)
GUI_TEST_CLASS_DECLARATION(test_1212)
GUI_TEST_CLASS_DECLARATION(test_1212_1)

GUI_TEST_CLASS_DECLARATION(test_1252)
GUI_TEST_CLASS_DECLARATION(test_1252_1)

GUI_TEST_CLASS_DECLARATION(test_1255)

GUI_TEST_CLASS_DECLARATION(test_1262)

GUI_TEST_CLASS_DECLARATION(test_1475)

GUI_TEST_CLASS_DECLARATION(test_1508)
GUI_TEST_CLASS_DECLARATION(test_1527)
GUI_TEST_CLASS_DECLARATION(test_1527_1)

GUI_TEST_CLASS_DECLARATION(test_1622)

GUI_TEST_CLASS_DECLARATION(test_1689)
GUI_TEST_CLASS_DECLARATION(test_1701)
GUI_TEST_CLASS_DECLARATION(test_1703)
GUI_TEST_CLASS_DECLARATION(test_1708)
GUI_TEST_CLASS_DECLARATION(test_1720)
GUI_TEST_CLASS_DECLARATION(test_1808)
GUI_TEST_CLASS_DECLARATION(test_1811)
GUI_TEST_CLASS_DECLARATION(test_1811_1)
GUI_TEST_CLASS_DECLARATION(test_1813)
GUI_TEST_CLASS_DECLARATION(test_1821)
GUI_TEST_CLASS_DECLARATION(test_1859)
GUI_TEST_CLASS_DECLARATION(test_1860)
GUI_TEST_CLASS_DECLARATION(test_1865)
GUI_TEST_CLASS_DECLARATION(test_1883)
GUI_TEST_CLASS_DECLARATION(test_1884)

GUI_TEST_CLASS_DECLARATION(test_1886_1)
GUI_TEST_CLASS_DECLARATION(test_1886_2)

GUI_TEST_CLASS_DECLARATION(test_1897)
GUI_TEST_CLASS_DECLARATION(test_1919)
GUI_TEST_CLASS_DECLARATION(test_1921)
GUI_TEST_CLASS_DECLARATION(test_1924)
GUI_TEST_CLASS_DECLARATION(test_1986)

GUI_TEST_CLASS_DECLARATION(test_2006)
GUI_TEST_CLASS_DECLARATION(test_2007)

GUI_TEST_CLASS_DECLARATION(test_2012)

GUI_TEST_CLASS_DECLARATION(test_2021_1)
GUI_TEST_CLASS_DECLARATION(test_2021_2)
GUI_TEST_CLASS_DECLARATION(test_2021_3)
GUI_TEST_CLASS_DECLARATION(test_2021_4)
GUI_TEST_CLASS_DECLARATION(test_2021_5)
GUI_TEST_CLASS_DECLARATION(test_2021_6)
GUI_TEST_CLASS_DECLARATION(test_2021_7)
GUI_TEST_CLASS_DECLARATION(test_2021_8)
GUI_TEST_CLASS_DECLARATION(test_2021_9)


GUI_TEST_CLASS_DECLARATION(test_2024)
GUI_TEST_CLASS_DECLARATION(test_2026)
GUI_TEST_CLASS_DECLARATION(test_2030)
GUI_TEST_CLASS_DECLARATION(test_2032)
GUI_TEST_CLASS_DECLARATION(test_2049)
GUI_TEST_CLASS_DECLARATION(test_2070)
GUI_TEST_CLASS_DECLARATION(test_2077)
GUI_TEST_CLASS_DECLARATION(test_2089)
GUI_TEST_CLASS_DECLARATION(test_2091)
GUI_TEST_CLASS_DECLARATION(test_2093_1)
GUI_TEST_CLASS_DECLARATION(test_2093_2)
GUI_TEST_CLASS_DECLARATION(test_2100_1)
GUI_TEST_CLASS_DECLARATION(test_2100_2)
GUI_TEST_CLASS_DECLARATION(test_2100_3)
GUI_TEST_CLASS_DECLARATION(test_2122)
GUI_TEST_CLASS_DECLARATION(test_2124)
GUI_TEST_CLASS_DECLARATION(test_2128)
GUI_TEST_CLASS_DECLARATION(test_2128_1)
GUI_TEST_CLASS_DECLARATION(test_2138)
GUI_TEST_CLASS_DECLARATION(test_2140)
GUI_TEST_CLASS_DECLARATION(test_2144)
GUI_TEST_CLASS_DECLARATION(test_2150)
GUI_TEST_CLASS_DECLARATION(test_2152)
GUI_TEST_CLASS_DECLARATION(test_2156)
GUI_TEST_CLASS_DECLARATION(test_2157)
GUI_TEST_CLASS_DECLARATION(test_2160)
GUI_TEST_CLASS_DECLARATION(test_2163)
GUI_TEST_CLASS_DECLARATION(test_2164)
GUI_TEST_CLASS_DECLARATION(test_2165)
GUI_TEST_CLASS_DECLARATION(test_2167)
GUI_TEST_CLASS_DECLARATION(test_2169)
GUI_TEST_CLASS_DECLARATION(test_2171)
GUI_TEST_CLASS_DECLARATION(test_2172)
GUI_TEST_CLASS_DECLARATION(test_2174)
GUI_TEST_CLASS_DECLARATION(test_2186)
GUI_TEST_CLASS_DECLARATION(test_2187)
GUI_TEST_CLASS_DECLARATION(test_2188)
GUI_TEST_CLASS_DECLARATION(test_2202)
GUI_TEST_CLASS_DECLARATION(test_2224)
GUI_TEST_CLASS_DECLARATION(test_2224_flow)
GUI_TEST_CLASS_DECLARATION(test_2225_1)
GUI_TEST_CLASS_DECLARATION(test_2225_2)
GUI_TEST_CLASS_DECLARATION(test_2259)
GUI_TEST_CLASS_DECLARATION(test_2266_1)
GUI_TEST_CLASS_DECLARATION(test_2267_1)
GUI_TEST_CLASS_DECLARATION(test_2267_2)
GUI_TEST_CLASS_DECLARATION(test_2268)
GUI_TEST_CLASS_DECLARATION(test_2269)
GUI_TEST_CLASS_DECLARATION(test_2270)
GUI_TEST_CLASS_DECLARATION(test_2281)
GUI_TEST_CLASS_DECLARATION(test_2282)
GUI_TEST_CLASS_DECLARATION(test_2284)
GUI_TEST_CLASS_DECLARATION(test_2292)
GUI_TEST_CLASS_DECLARATION(test_2306)
GUI_TEST_CLASS_DECLARATION(test_2309)
GUI_TEST_CLASS_DECLARATION(test_2316)
GUI_TEST_CLASS_DECLARATION(test_2318)
GUI_TEST_CLASS_DECLARATION(test_2351)
GUI_TEST_CLASS_DECLARATION(test_2352)
GUI_TEST_CLASS_DECLARATION(test_2360)
GUI_TEST_CLASS_DECLARATION(test_2364)
GUI_TEST_CLASS_DECLARATION(test_2375)
GUI_TEST_CLASS_DECLARATION(test_2377)
GUI_TEST_CLASS_DECLARATION(test_2378)
GUI_TEST_CLASS_DECLARATION(test_2378_1)
GUI_TEST_CLASS_DECLARATION(test_2379)
GUI_TEST_CLASS_DECLARATION(test_2382)
GUI_TEST_CLASS_DECLARATION(test_2382_1)
GUI_TEST_CLASS_DECLARATION(test_2392)
GUI_TEST_CLASS_DECLARATION(test_2401)
GUI_TEST_CLASS_DECLARATION(test_2406)
GUI_TEST_CLASS_DECLARATION(test_2407)
GUI_TEST_CLASS_DECLARATION(test_2410)
GUI_TEST_CLASS_DECLARATION(test_2415)
GUI_TEST_CLASS_DECLARATION(test_2460)
GUI_TEST_CLASS_DECLARATION(test_2475)
GUI_TEST_CLASS_DECLARATION(test_2519)

#undef GUI_TEST_PREFIX
}

} //namespace

#endif
