/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2015 UniPro <ugene@unipro.ru>
 * http://ugene.unipro.ru
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_1_1000_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_1_1000_H_

#include <U2Test/GUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_PREFIX
#define GUI_TEST_PREFIX "GUITest_regression_scenarios_"

GUI_TEST_CLASS_DECLARATION(test_0407)
GUI_TEST_CLASS_DECLARATION(test_0490)

GUI_TEST_CLASS_DECLARATION(test_0677)
GUI_TEST_CLASS_DECLARATION(test_0678)
GUI_TEST_CLASS_DECLARATION(test_0685)

GUI_TEST_CLASS_DECLARATION(test_0700)
GUI_TEST_CLASS_DECLARATION(test_0734)
GUI_TEST_CLASS_DECLARATION(test_0746)
GUI_TEST_CLASS_DECLARATION(test_0774)
GUI_TEST_CLASS_DECLARATION(test_0776)
GUI_TEST_CLASS_DECLARATION(test_0778)
GUI_TEST_CLASS_DECLARATION(test_0779)

GUI_TEST_CLASS_DECLARATION(test_0801)
GUI_TEST_CLASS_DECLARATION(test_0812)
GUI_TEST_CLASS_DECLARATION(test_0814)
GUI_TEST_CLASS_DECLARATION(test_0818)
GUI_TEST_CLASS_DECLARATION(test_0821)
GUI_TEST_CLASS_DECLARATION(test_0828)
GUI_TEST_CLASS_DECLARATION(test_0829)
GUI_TEST_CLASS_DECLARATION(test_0844)
GUI_TEST_CLASS_DECLARATION(test_0854)
GUI_TEST_CLASS_DECLARATION(test_0858)
GUI_TEST_CLASS_DECLARATION(test_0861_1)
GUI_TEST_CLASS_DECLARATION(test_0861_2)
GUI_TEST_CLASS_DECLARATION(test_0861_3)
GUI_TEST_CLASS_DECLARATION(test_0861_4)
GUI_TEST_CLASS_DECLARATION(test_0866)
GUI_TEST_CLASS_DECLARATION(test_0871)
GUI_TEST_CLASS_DECLARATION(test_0873)
GUI_TEST_CLASS_DECLARATION(test_0878)
GUI_TEST_CLASS_DECLARATION(test_0882)
GUI_TEST_CLASS_DECLARATION(test_0886)
GUI_TEST_CLASS_DECLARATION(test_0889)
GUI_TEST_CLASS_DECLARATION(test_0896)
GUI_TEST_CLASS_DECLARATION(test_0898)
GUI_TEST_CLASS_DECLARATION(test_0899)

GUI_TEST_CLASS_DECLARATION(test_0908)
GUI_TEST_CLASS_DECLARATION(test_0910)
GUI_TEST_CLASS_DECLARATION(test_0928)
GUI_TEST_CLASS_DECLARATION(test_0930)
GUI_TEST_CLASS_DECLARATION(test_0935)
GUI_TEST_CLASS_DECLARATION(test_0938)
GUI_TEST_CLASS_DECLARATION(test_0940)
GUI_TEST_CLASS_DECLARATION(test_0941)
GUI_TEST_CLASS_DECLARATION(test_0947)
GUI_TEST_CLASS_DECLARATION(test_0948)
GUI_TEST_CLASS_DECLARATION(test_0952)
GUI_TEST_CLASS_DECLARATION(test_0958)
GUI_TEST_CLASS_DECLARATION(test_0965)
GUI_TEST_CLASS_DECLARATION(test_0967_1)
GUI_TEST_CLASS_DECLARATION(test_0967_2)
GUI_TEST_CLASS_DECLARATION(test_0967_3)
GUI_TEST_CLASS_DECLARATION(test_0969)
GUI_TEST_CLASS_DECLARATION(test_0970)
GUI_TEST_CLASS_DECLARATION(test_0981_1)
GUI_TEST_CLASS_DECLARATION(test_0981_2)
GUI_TEST_CLASS_DECLARATION(test_0986)
GUI_TEST_CLASS_DECLARATION(test_0986_1)
GUI_TEST_CLASS_DECLARATION(test_0986_2)
GUI_TEST_CLASS_DECLARATION(test_0986_3)
GUI_TEST_CLASS_DECLARATION(test_0986_4)
GUI_TEST_CLASS_DECLARATION(test_0994)

#undef GUI_TEST_PREFIX

}   // namespace GUITest_regression_scenarios

}   // namespace U2

#endif // _U2_GT_TESTS_REGRESSION_SCENARIOS_1_1000_H_
