/**
 * UGENE - Integrated Bioinformatics Tools.
 * Copyright (C) 2008-2015 UniPro <ugene@unipro.ru>
 * http://ugene.unipro.ru
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
 * MA 02110-1301, USA.
 */

#ifndef _U2_GT_TESTS_REGRESSION_SCENARIOS_4001_5000_H_
#define _U2_GT_TESTS_REGRESSION_SCENARIOS_4001_5000_H_

#include <U2Test/GUITestBase.h>

namespace U2 {

namespace GUITest_regression_scenarios {

#undef GUI_TEST_PREFIX
#define GUI_TEST_PREFIX "GUITest_regression_scenarios_"

GUI_TEST_CLASS_DECLARATION(test_4007)
GUI_TEST_CLASS_DECLARATION(test_4008)
GUI_TEST_CLASS_DECLARATION(test_4009)
GUI_TEST_CLASS_DECLARATION(test_4011)
GUI_TEST_CLASS_DECLARATION(test_4010)
GUI_TEST_CLASS_DECLARATION(test_4013)
GUI_TEST_CLASS_DECLARATION(test_4022)
GUI_TEST_CLASS_DECLARATION(test_4026)
GUI_TEST_CLASS_DECLARATION(test_4030)
GUI_TEST_CLASS_DECLARATION(test_4033)
GUI_TEST_CLASS_DECLARATION(test_4034)
GUI_TEST_CLASS_DECLARATION(test_4035)
GUI_TEST_CLASS_DECLARATION(test_4036)
GUI_TEST_CLASS_DECLARATION(test_4045)
GUI_TEST_CLASS_DECLARATION(test_4046)
GUI_TEST_CLASS_DECLARATION(test_4059)
GUI_TEST_CLASS_DECLARATION(test_4064)
GUI_TEST_CLASS_DECLARATION(test_4065)
GUI_TEST_CLASS_DECLARATION(test_4070)
GUI_TEST_CLASS_DECLARATION(test_4071)
GUI_TEST_CLASS_DECLARATION(test_4072)
GUI_TEST_CLASS_DECLARATION(test_4084)
GUI_TEST_CLASS_DECLARATION(test_4091)
GUI_TEST_CLASS_DECLARATION_SET_TIMEOUT(test_4093, 480000)
GUI_TEST_CLASS_DECLARATION(test_4095)
GUI_TEST_CLASS_DECLARATION(test_4096)
GUI_TEST_CLASS_DECLARATION(test_4097)
GUI_TEST_CLASS_DECLARATION(test_4099)

GUI_TEST_CLASS_DECLARATION(test_4100)
GUI_TEST_CLASS_DECLARATION(test_4104)
GUI_TEST_CLASS_DECLARATION(test_4106)
GUI_TEST_CLASS_DECLARATION(test_4110)
GUI_TEST_CLASS_DECLARATION(test_4111)
GUI_TEST_CLASS_DECLARATION(test_4113)
GUI_TEST_CLASS_DECLARATION(test_4116)
GUI_TEST_CLASS_DECLARATION(test_4117)
GUI_TEST_CLASS_DECLARATION(test_4118)
GUI_TEST_CLASS_DECLARATION(test_4120)
GUI_TEST_CLASS_DECLARATION(test_4121)
GUI_TEST_CLASS_DECLARATION(test_4122)
GUI_TEST_CLASS_DECLARATION(test_4124)
GUI_TEST_CLASS_DECLARATION(test_4127)
GUI_TEST_CLASS_DECLARATION(test_4131)
GUI_TEST_CLASS_DECLARATION(test_4134)
GUI_TEST_CLASS_DECLARATION(test_4141)
GUI_TEST_CLASS_DECLARATION(test_4148)
GUI_TEST_CLASS_DECLARATION(test_4150)
GUI_TEST_CLASS_DECLARATION(test_4151)
GUI_TEST_CLASS_DECLARATION(test_4153)
GUI_TEST_CLASS_DECLARATION(test_4156)
GUI_TEST_CLASS_DECLARATION(test_4160)
GUI_TEST_CLASS_DECLARATION(test_4164)
GUI_TEST_CLASS_DECLARATION(test_4170)
GUI_TEST_CLASS_DECLARATION(test_4179)

GUI_TEST_CLASS_DECLARATION(test_4209)
GUI_TEST_CLASS_DECLARATION(test_4218)
GUI_TEST_CLASS_DECLARATION(test_4218_1)
GUI_TEST_CLASS_DECLARATION(test_4221)
GUI_TEST_CLASS_DECLARATION(test_4244)
GUI_TEST_CLASS_DECLARATION(test_4266)
GUI_TEST_CLASS_DECLARATION(test_4272)
GUI_TEST_CLASS_DECLARATION(test_4284)
GUI_TEST_CLASS_DECLARATION(test_4295)

GUI_TEST_CLASS_DECLARATION(test_4323_1)
GUI_TEST_CLASS_DECLARATION(test_4323_2)
GUI_TEST_CLASS_DECLARATION(test_4323_3)
GUI_TEST_CLASS_DECLARATION(test_4323_4)
GUI_TEST_CLASS_DECLARATION(test_4325)
GUI_TEST_CLASS_DECLARATION(test_4383)

#undef GUI_TEST_PREFIX

}   // namespace GUITest_regression_scenarios

}   // namespace U2

#endif // _U2_GT_TESTS_REGRESSION_SCENARIOS_4001_5000_H_
