######################################################################
# Automatically generated by qmake (2.01a) Tue Jun 29 16:30:38 2010
######################################################################

include (external_tool_support.pri)
# Input
HEADERS += src/ExternalToolSupportPlugin.h \
           src/ExternalToolSupportSettings.h \
           src/ExternalToolSupportSettingsController.h \
           src/ExternalToolRunTask.h \
           src/TaskLocalStorage.h \
           src/utils/ExportTasks.h \
           src/utils/ExternalToolSupportAction.h \
           src/utils/BlastRunCommonDialog.h \
           src/utils/BlastTaskSettings.h \
           src/utils/ExternalToolValidateTask.h \
           src/clustalw/ClustalWSupport.h \
           src/clustalw/ClustalWSupportTask.h \
           src/clustalw/ClustalWSupportRunDialog.h \
           src/clustalw/ClustalWWorker.h \
           src/mafft/MAFFTSupport.h \
           src/mafft/MAFFTSupportTask.h \
           src/mafft/MAFFTSupportRunDialog.h \
           src/mafft/MAFFTWorker.h \
           src/tcoffee/TCoffeeSupport.h \
           src/tcoffee/TCoffeeSupportTask.h \
           src/tcoffee/TCoffeeSupportRunDialog.h \
           src/tcoffee/TCoffeeWorker.h \
           src/blast/FormatDBSupport.h \
           src/blast/FormatDBSupportRunDialog.h \
           src/blast/FormatDBSupportTask.h \
           src/blast/BlastAllSupport.h \
           src/blast/BlastAllSupportRunDialog.h \
           src/blast/BlastAllSupportTask.h \
           src/blast/BlastAllWorker.h \
           src/ETSProjectViewItemsContoller.h \
           src/blast_plus/BlastPlusSupport.h \
           src/blast_plus/BlastPlusSupportRunDialog.h \
           src/blast_plus/BlastPlusSupportCommonTask.h \
           src/blast_plus/BlastNPlusSupportTask.h \
           src/blast_plus/BlastPPlusSupportTask.h \
           src/blast_plus/BlastXPlusSupportTask.h \
           src/blast_plus/TBlastNPlusSupportTask.h \
           src/blast_plus/TBlastXPlusSupportTask.h \
           src/blast_plus/BlastPlusWorker.h \
           src/blast_plus/RPSBlastSupportTask.h

SOURCES += src/ExternalToolSupportPlugin.cpp \
           src/ExternalToolSupportSettings.cpp \
           src/ExternalToolSupportSettingsController.cpp \
           src/ExternalToolRunTask.cpp \
           src/TaskLocalStorage.cpp \
           src/utils/ExportTasks.cpp \
           src/utils/ExternalToolSupportAction.cpp \
           src/utils/BlastRunCommonDialog.cpp \
           src/utils/BlastTaskSettings.cpp \
           src/utils/ExternalToolValidateTask.cpp \
           src/clustalw/ClustalWSupport.cpp \
           src/clustalw/ClustalWSupportTask.cpp \
           src/clustalw/ClustalWSupportRunDialog.cpp \
           src/clustalw/ClustalWWorker.cpp \
           src/mafft/MAFFTSupport.cpp \
           src/mafft/MAFFTSupportTask.cpp \
           src/mafft/MAFFTSupportRunDialog.cpp \
           src/mafft/MAFFTWorker.cpp \
           src/tcoffee/TCoffeeSupport.cpp \
           src/tcoffee/TCoffeeSupportTask.cpp \
           src/tcoffee/TCoffeeSupportRunDialog.cpp \
           src/tcoffee/TCoffeeWorker.cpp \
           src/blast/FormatDBSupport.cpp \
           src/blast/FormatDBSupportRunDialog.cpp \
           src/blast/FormatDBSupportTask.cpp \
           src/blast/BlastAllSupport.cpp \
           src/blast/BlastAllSupportRunDialog.cpp \
           src/blast/BlastAllSupportTask.cpp \
           src/blast/BlastAllWorker.cpp \
           src/ETSProjectViewItemsContoller.cpp \
           src/blast_plus/BlastPlusSupport.cpp \
           src/blast_plus/BlastPlusSupportRunDialog.cpp \
           src/blast_plus/BlastPlusSupportCommonTask.cpp \
           src/blast_plus/BlastNPlusSupportTask.cpp \
           src/blast_plus/BlastPPlusSupportTask.cpp \
           src/blast_plus/BlastXPlusSupportTask.cpp \
           src/blast_plus/TBlastNPlusSupportTask.cpp \
           src/blast_plus/TBlastXPlusSupportTask.cpp \
           src/blast_plus/BlastPlusWorker.cpp \
           src/blast_plus/RPSBlastSupportTask.cpp

FORMS +=   src/ui/ETSSettingsWidget.ui \
           src/ui/ClustalWSupportRunDialog.ui \
           src/ui/MAFFTSupportRunDialog.ui \
           src/ui/TCoffeeSupportRunDialog.ui \
           src/ui/FormatDBSupportRunDialog.ui \
           src/ui/BlastAllSupportDialog.ui

RESOURCES += external_tool_support.qrc
TRANSLATIONS += transl/english.ts transl/russian.ts