#!/bin/bash

appname=ugenecl

# Check if '-ui' parameter is present. 
# If it does exclude it from the list of parameters
# and use ugeneui instead of ugenecl

params=()

while [[ $# -gt 0 ]];
do
    if [ "$1" = "-ui" ]; then
        appname=ugeneui
    else
        params+=("$1")
    fi
    shift
done

dirname=$(dirname `readlink -f $0`)

tmp="${dirname#?}"

if [ "${dirname%$tmp}" != "/" ]; then
    dirname=$PWD/$dirname
fi

$dirname/$appname "${params[@]}"