include (api_tests.pri)

# Input
HEADERS += \
    src/ApiTestsPlugin.h \
    src/unittest.h \
    src/core/datatype/annotations/AnnotationGroupUnitTests.h \
    src/core/datatype/annotations/AnnotationUnitTests.h \
    src/core/datatype/msa/MAlignmentUnitTests.h \
    src/core/datatype/msa/MAlignmentRowUnitTests.h \
    src/core/dbi/DbiTest.h \
    src/core/dbi/assembly/AssemblyDbiTestUtil.h \
    src/core/dbi/assembly/AssemblyDbiUnitTests.h \
    src/core/dbi/sequence/SequenceDbiUnitTests.h \
    src/core/dbi/attribute/AttributeDbiUnitTests.h \
    src/core/dbi/features/FeatureDbiUnitTests.h \
    src/core/dbi/msa/MsaDbiUnitTests.h \
    src/core/external_script/base_scheme_interface/CInterfaceManualTests.h \
    src/core/external_script/base_scheme_interface/CInterfaceSasTests.h \
    src/core/external_script/base_scheme_interface/SchemeSimilarityUtils.h \
    src/core/format/fastq/FastqUnitTests.h \
    src/core/format/genbank/LocationParserUnitTests.h \
    src/core/format/sqlite_msa_dbi/MsaDbiSQLiteSpecificUnitTests.h \
    src/core/format/sqlite_object_dbi/SQLiteObjectDbiUnitTests.h \
    src/core/gobjects/FeaturesTableObjectUnitTest.h \
    src/core/gobjects/MAlignmentObjectUnitTests.h \
    src/core/util/MAlignmentImporterExporterUnitTests.h \
    src/UnitTestSuite.h \  
    src/core/util/MsaDbiUtilsUnitTests.h \
    src/core/util/MsaUtilsUnitTests.h \
    src/core/format/sqlite_mod_dbi/ModDbiSQLiteSpecificUnitTests.h \
    src/core/format/sqlite_sequence_dbi/SequenceDbiSQLiteSpecificUnitTests.h
SOURCES += \
    src/ApiTestsPlugin.cpp \
    src/core/datatype/annotations/AnnotationGroupUnitTests.cpp \
    src/core/datatype/annotations/AnnotationUnitTests.cpp \
    src/core/datatype/msa/MAlignmentUnitTests.cpp \
    src/core/datatype/msa/MAlignmentRowUnitTests.cpp \
    src/core/dbi/DbiTest.cpp \
    src/core/dbi/assembly/AssemblyDbiTestUtil.cpp \
    src/core/dbi/assembly/AssemblyDbiUnitTests.cpp \
    src/core/dbi/sequence/SequenceDbiUnitTests.cpp \
    src/core/dbi/attribute/AttributeDbiUnitTests.cpp \
    src/core/dbi/msa/MsaDbiUnitTests.cpp \
    src/core/external_script/base_scheme_interface/CInterfaceManualTests.cpp \
    src/core/external_script/base_scheme_interface/CInterfaceSasTests.cpp \
    src/core/external_script/base_scheme_interface/SchemeSimilarityUtils.cpp \
    src/core/format/fastq/FastqUnitTests.cpp \
    src/core/format/genbank/LocationParserUnitTests.cpp \
    src/core/format/sqlite_msa_dbi/MsaDbiSQLiteSpecificUnitTests.cpp \
    src/core/format/sqlite_object_dbi/SQLiteObjectDbiUnitTests.cpp \
    src/core/gobjects/FeaturesTableObjectUnitTest.cpp \
    src/core/gobjects/MAlignmentObjectUnitTests.cpp \
    src/core/util/MAlignmentImporterExporterUnitTests.cpp \
    src/UnitTestSuite.cpp \  
    src/core/util/MsaDbiUtilsUnitTests.cpp \
    src/core/util/MsaUtilsUnitTests.cpp \
    src/core/format/sqlite_mod_dbi/ModDbiSQLiteSpecificUnitTests.cpp \
    src/core/format/sqlite_sequence_dbi/SequenceDbiSQLiteSpecificUnitTests.cpp